### ISSUE TITLE
Plugin doesn't build on Debian 8

### ISSUE THREAD

**Issue by jasondunsmore** [dprotti/infinity-plugin#2]
Hi, I'm having trouble building the plugin on Debian Jessie:

```
$ ./configure --prefix=/usr
bash: ./configure: No such file or directory
$ autoconf
configure.ac:5: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:58: error: possibly undefined macro: AC_DISABLE_STATIC
configure.ac:97: error: possibly undefined macro: AM_PATH_SDL
configure.ac:159: error: possibly undefined macro: AM_GLIB_GNU_GETTEXT
$ ./configure --prefix=/usr
./configure: line 2314: syntax error near unexpected token `1.9.0'
./configure: line 2314: `AM_INIT_AUTOMAKE(1.9.0 dist-bzip2)'
```

HEAD is currently at bf13d4b1d7c.

**Comment by dprotti** [comment]
Thanks for reporting this.
I do not have access to a Debian Jessie now.

Please try running `aclocal` first. Then run autoconf (eventually you need to run automake and autoheader as well).
If you have autoreconf command try running simply autoreconf.

Let me know if this works for you.

Regards.

**Comment by dprotti** [comment]
Hi Jason.

Did the steps given in the above instructions work for you?
